user:
  jay:
    username: jay
    password: 123456
  william:
    username: william
    password: 1234abcd!
  failure:
    username: william
    password: william
mysql:
  db: trading_system
  host: 119.91.206.145
  password: 123456
  port: 3306
  user: root

url: http://www.tcpjwtester.top
