user:
  jay:
    username: jay
    password: 123456
  william:
    username: william
    password: 1234abcd!
mysql:
  db: autotest
  host: localhost
  password: 123456
  port: 3306
  user: root

url: http://www.tcpjwtester.top/login?url=%2F
